-- CASE STUDY: Parch and Posey
-- The dataset is made up of 5 tables which include;
-- accounts (details about the accounts that place are associated with the different orders)
-- orders(products ordered, their quantities and the revenue generated)
-- region(the regions where the sales rep come from)
-- sales reps(the sales reps that work for the company identified by their unique id)
-- web events (the different channels that orders were placed)
-- The insights generated will help to track the accounts that have been active in their purchases
-- and also track sales rep performance over the years to improve sales


-- QUESTIONS

-- 1. How much Product has been ordered?

SELECT SUM(total) AS total_orders
FROM public.orders;

-- 2. How much product has been ordered over the years

SELECT  order_year, SUM(total) AS total_orders
FROM public.orders
GROUP BY order_year
ORDER BY total_orders DESC;


-- 3. How much revenue has been generated?

SELECT SUM(total_amt_usd) AS total_revenue
FROM public.orders;


-- 4. How much revenue has been generated over the years?

SELECT order_year, SUM(total_amt_usd) AS total_revenue
FROM public.orders
GROUP BY order_year
ORDER BY total_revenue DESC;


-- 5. What is the total order of each product?

SELECT 
	SUM(standard_qty) AS total_standard,
	SUM(poster_qty) AS total_poster,
	SUM(gloss_qty) AS total_gloss
FROM public.orders;
-- standard was the most ordered of all the products
-- standard>gloss>poster

-- 6. What is the total order of each product over the years?

SELECT order_year,
	SUM(standard_qty) AS total_standard,
	SUM(poster_qty) AS total_poster,
	SUM(gloss_qty) AS total_gloss
FROM public.orders
GROUP BY order_year
ORDER BY order_year;


-- 7. What is the revenue generated for each product?

SELECT
	SUM(standard_amt_usd) AS standard_revenue,
	SUM(poster_amt_usd) AS poster_revenue,
	SUM(gloss_amt_usd) AS gloss_revenue
FROM public.orders;
-- standard>gloss>poster


-- 8. What is the revenue generated by products over the years?

SELECT order_year,
	SUM(standard_amt_usd) AS standard_revenue,
	SUM(poster_amt_usd) AS poster_revenue,
	SUM(gloss_amt_usd) AS gloss_revenue
FROM public.orders
GROUP BY order_year
ORDER BY order_year;

-- 9. What months were the highest sales and revenue generated?

SELECT order_month, order_year,
	SUM(total) AS total_sales,
	SUM(total_amt_usd) AS total_revenue
FROM public.orders
GROUP BY order_month, order_year
ORDER BY total_revenue DESC
LIMIT 10;
-- top sales and revenue were recorded in 2016


-- 10. What accounts had the highest orders and generated highest sales?

SELECT accounts.name, 
	SUM(orders.total) AS total_orders,
	SUM(orders.total_amt_usd) AS total_revenue
FROM public.accounts AS accounts
LEFT JOIN public.orders AS orders ON accounts.id = orders.account_id
LEFT JOIN public.sales_reps AS sales_rep ON accounts.sales_rep_id = sales_rep.id
WHERE orders.total IS NOT NULL
GROUP BY accounts.name
ORDER BY total_revenue DESC
LIMIT 10;


-- 11. Who are the sales rep and regions behind the accounts that generated highest orders and generated highest sales?

SELECT accounts.name, sales_rep.name, region.name,
	SUM(orders.total) AS total_orders,
	SUM(orders.total_amt_usd) AS total_revenue
FROM public.accounts AS accounts
LEFT JOIN public.orders AS orders ON accounts.id = orders.account_id
LEFT JOIN public.sales_reps AS sales_rep ON accounts.sales_rep_id = sales_rep.id
LEFT JOIN public.region AS region ON sales_rep.region_id = region.id
WHERE orders.total IS NOT NULL
GROUP BY accounts.name, sales_rep.name, region.name
ORDER BY total_revenue DESC
LIMIT 10;


-- 12. Who are the sales rep with the highest revenue?

SELECT sales_rep.name, region.name,
	SUM(orders.total) AS total_orders,
	SUM(orders.total_amt_usd) AS total_revenue
FROM public.accounts AS accounts
LEFT JOIN public.orders AS orders ON accounts.id = orders.account_id
LEFT JOIN public.sales_reps AS sales_rep ON accounts.sales_rep_id = sales_rep.id
LEFT JOIN public.region AS region ON sales_rep.region_id = region.id
WHERE orders.total IS NOT NULL
GROUP BY sales_rep.name, region.name
ORDER BY total_revenue DESC
LIMIT 10;


-- 13 What regions generated the highest revenue?

SELECT region.name,
	SUM(orders.total) AS total_orders,
	SUM(orders.total_amt_usd) AS total_revenue
FROM public.accounts AS accounts
LEFT JOIN public.orders AS orders ON accounts.id = orders.account_id
LEFT JOIN public.sales_reps AS sales_rep ON accounts.sales_rep_id = sales_rep.id
LEFT JOIN public.region AS region ON sales_rep.region_id = region.id
WHERE orders.total IS NOT NULL
GROUP BY region.name
ORDER BY total_revenue DESC;
-- Northeast > Southeast > West > Midwest


-- 14. What regions generated the highest revenue over the years?

SELECT region.name, order_year,
	SUM(orders.total) AS total_orders,
	SUM(orders.total_amt_usd) AS total_revenue
FROM public.accounts AS accounts
LEFT JOIN public.orders AS orders ON accounts.id = orders.account_id
LEFT JOIN public.sales_reps AS sales_rep ON accounts.sales_rep_id = sales_rep.id
LEFT JOIN public.region AS region ON sales_rep.region_id = region.id
WHERE orders.total IS NOT NULL
GROUP BY region.name, order_year
ORDER BY order_year, total_revenue DESC;

-- Highest revenue was generted by Southeast in 2012, 2014, and 2017
-- Highest revenue was generated by North east in 2015 and 2016

-- 15. What amount of sales and revenue were generated by the channels?

SELECT web_events.channel,
	SUM(orders.total) AS total_orders,
	SUM(orders.total_amt_usd) AS total_revenue
FROM public.accounts AS accounts
LEFT JOIN public.orders AS orders ON accounts.id = orders.account_id
LEFT JOIN public.web_events AS web_events ON accounts.id = web_events.account_id
WHERE orders.total IS NOT NULL
GROUP BY web_events.channel
ORDER BY  total_revenue DESC;

-- direct > facebook > organic > adwords > twitter > banner


-- 16. How did the channels generate revenue over years?

SELECT web_events.channel, web_events.order_year,
	SUM(orders.total) AS total_orders,
	SUM(orders.total_amt_usd) AS total_revenue
FROM public.accounts AS accounts
LEFT JOIN public.orders AS orders ON accounts.id = orders.account_id
LEFT JOIN public.web_events AS web_events ON accounts.id = web_events.account_id
WHERE orders.total IS NOT NULL
GROUP BY web_events.channel, web_events.order_year
ORDER BY order_year, total_revenue DESC;

-- consistently over the years direct has generated highest revenue

-- 17. What web events generated most traffic?

SELECT channel, COUNT(id) AS traffic_generated
FROM public.web_events
GROUP BY channel
ORDER BY traffic_generated DESC;

-- direct > facebook > organic > adwords  > banner> twitter

-- 17. What web events generated most traffic each year?
SELECT channel, order_year, COUNT(id) AS traffic_generated
FROM public.web_events
GROUP BY channel, order_year
ORDER BY order_year, traffic_generated DESC;


-- INSIGHTS
--	 Highest revenue was generated in 2016, which is followed by 2015 showing increased revenue trend
--	 Standard is the most ordered product followed by gloss then poster and the revenue generated follows same pattern
--	 EOG resources generated the highest resources followed by Mosiac while Nike generated the least revenue
--	 Arica Stoltzfus is the sales rep associated with the account that generated the highest revenue however Tia Amato has two accounts among the top 10 accounts
-- 	 Earlie Schleusner generated the highest revenue followed by Tia Amato
-- 	 Northeast generated the highest revenue followed by Southeast then West and Midwest
--	 Highest revenue was generted by Southeast in 2012, 2014, and 2017
--	 Highest revenue was generated by North east in 2015 and 2016
--	 direct generated the most revenue followed by facebook, organic, adwords, twitter, and banner
--	 consistently over the years direct has generated highest revenue
--	 direct generated the most trafic followed by facebook, organic, adwords, banner, and twitter


-- RECOMMENDATIONS
-- 	Invest in marketing and sales strategies that capitalize on the factors contributing to the revenue growth observed between 2015 and 2016. 
-- 	This may involve expanding successful products or increasing marketing campaigns
-- 	Prioritize the production, promotion, and sales of the Standard product, as it is the most ordered and highest revenue-generating product.
-- 	Strengthen relationships with high-revenue clients by offering tailored deals or loyalty programs to encourage continued and increased spending.
-- 	Analyze why least performingaccounts generates the least revenue and develop a targeted strategy to improve performance with this client.
-- 	Provide resources or training to low performing sales reps to help them reach high levels of success while rewarding high performing sales rep.
--  Focus sales and marketing efforts in the Northeast and Southeast regions, as they have consistently generated the highest revenues in key year
-- 	Additionally,opportunities to grow market share in the West and Midwest regions, where revenue generation is lower should be explored by tailoring products to regions
-- 	Direct channels has consistently generated the most revenue and traffic. This can be further optimized by improving customer personalization and targeted offers.
--  Evaluate the performance of lower-performing channels like Twitter and Banner ads to decide whether to improve them or reallocate resources to higher-performing channels.
-- 	Develop a multi-year strategy that focuses on sustaining and enhancing the momentum in regions and channels that have demonstrated high performance.
